version: '3'
services:
  solr:
    image: solr:8
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -c
      - -f
volumes:
  data:
